struct {
<<<<<<< HEAD
	ActualL2ATraffic                        int
	AdBlockConfig                           AbkConfig
	AddCreativeInURL                        bool
	AdditionFactor                          float64
	AdditionFactorClickLimit                float64
	AddSellerTagInUrl                       bool
	AddTemplateInURL                        bool
	AdjustDomainL2ATraffic                  int
	AdvertiserAuditing                      bool
	AdvertiserDetailClickThreshold          float64
	AdvertiserDetailExpiry                  float64
	AdvertiserExpiry                        int64
	AeroMultiplier                          float64
	AerospikeCache                          bool
	AerospikeFeedbackBlocked                bool
	AerospikeKeywordRPCReadPercentage       int
	AerospikeKwdStrategyPercent             int
	AerospikeReadStrategyPercent            int
	AllowUnknownSellerTagId                 bool
	AllowUnknownViewability                 bool
	AllowZeroBiasInFeedback                 bool
	AlternateMapTraffic                     int
	AlternateBaseMapToggle                  bool
	AlternateL2aBaseTraffic                 map[string]int
	AlternateL2aBaseL2aFiles                map[string]string
	AlternateL2aBaseWriteL2aFiles           map[string]string
	AlwaysAddToBase                         bool
	ApplyBrowserMultiplier                  bool
	ApplyManualPattern                      bool
	AuctionType1Multiplier                  float64
	AuctionType2Multiplier                  float64
	AutoModelUsed                           bool
	BaseMapSwitchAdclickThreshold           int
	BehaviouralTargetingConfig              BehaviouralTargetingConfig
	BiasClickThreshold                      float64
	Biases                                  string
	BiasFeedbackTill                        float64
	BiasModelName                           []string
	BiasModelTraffic                        []int
	BiasModelTrafficOverall                 int
	BidderRPCTraffic                        int
	BidFloorInflationDomains                []string
	BidFloorInflationTraffic                int
	BidFloorInflationAmount                 float64
	BlockDueToLogging                       bool
	BlockedTemplates                        []string
	BlockedTrafficPercent                   int
	BlockMaxProvider                        bool
	BlockNonUTM                             bool
	BlockSpam                               bool
	BrowserLevelKeywordTraffic              int
	BrowserRPCTraffic                       int
	ByPassKeywordClicksTrafficPercentage    int
	CanadaKeywords                          bool
	CascadingL2AClickRange                  []float64
	CascadingL2AClickThreshold              float64
	CascadingR2AClickThreshold              float64
	CascadingR2AWeight                      float64
	CatboostL2AModelClickThreshold          float64
	CatboostL2AModelTraffic                 int
	CatboostL2AUrlSubTraffic                int
	CatboostModelName                       string
	CatboostR2AModelName                    string
	CatboostRPCModelName                    string
	CbsL2aApiPath                           string
	CeaseExplorationPageviewFactor          float64
	ClickedKeywordBuckets                   int
	ClickedKeywordsExpiry                   int64
	ClickedKeywordsThreshold                float64
	ClickedKeywordsWeight                   float64
	ClickedKeywordsWhitelistLimit           int64
	ClickRatio                              float64
	CommercialPatternTrafficPercentage      int
	ConsensusClickThreshold                 float64
	ConsiderFeatureMapping                  bool
	ConsiderTopLevelR2A                     bool
	CountryLevelStopLoss                    map[string]float64
	CreativeLevelKeywords                   bool
	CustomerURLRPCTraffic                   int
	DeviceOSThreshold                       float64
	DisableHomePageBlocking                 bool
	DisableRPCExploration                   bool
	Disagreement                            float64
	DiscrepancyMultiplierEnabled            bool
	DisplayedKeywordBuckets                 int
	DisplayedKeywordsExpiry                 int64
	DisplayedKeywordsHalvingFactor          float64
	DisplayedKeywordsThreshold              float64
	DomainL2ARatioBoostTraffic              int
	DomainRPCTraffic                        int
	DynamicExplorationEnabled               bool
	DynamicMultiplierEnabled                bool
	EcpiTrafficPercentage                   int
	EnabledBiases                           []string
	ExploitationClickLowerLimit             float64
	ExploitationClickThreshold              float64
	ExploitationClickUpperLimit             float64
	ExploitationMinimumDepth                int
	ExploitationWeight                      float64
	ExploitationWeightThreshold             float64
	ExplorationClickThreshold               float64
	ExplorationHardCap                      float64
	ExplorationMaxL2ATraffic                int
	ExplorationMultiplier                   float64
	ExplorationPercent                      int
	ExplorationSpeedDamper                  float64
	FailoverEcpi                            float64
	FailoverR2A                             float64
	FailoverRPC                             float64
	FailoverRPM                             bool
	FailoverStrategyEnabled                 bool
	FailoverStrategyMultiplier              float64
	FeatureMappingBucketTraffic             int
	FeedbackTill                            float64
	FeedbackWeight                          float64
	FilterSlidingKeywords                   bool
	FloorPrice                              float64
	ForbesAdvisorRPCTraffic                 int
	ForbesRPCExpiry                         float64
	ForbesRPCRectify                        bool
	ForbesURLTransformation                 bool
	ForceTemplateId                         string
	ForcedProviderGroup                     string
	GlobalBiasFeedbackEnabled               bool
	GlobalBiasTrafficPercent                int
	GlobalClickLimit                        float64
	HardCap                                 float64
	HashUserAgent                           bool
	HierarchyMultiplier                     float64
	HourMultiplier                          map[string]float64
	IgnoreVisibility                        bool
	IgnoreZeroInfoDataTraffic               int
	IgnoreZeroInfoThreshold                 float64
	IhaPercentage                           int
	InitialWeight                           float64
	IntegrationBias                         bool
	IntegrationFile                         string
	IPBiasClickThreshold                    float64
	IPBiasViewsThreshold                    float64
	IPBiasLowerLimit                        float64
	IPBiasLimit                             float64
	IPBiasTraffic                           int
	IPBiasNonSpamTraffic                    int
	IPBiasFull                              bool
	IPBiasBClass                            bool
	IPStateBiasDisabled                     bool
	IPUnbiasEnabled                         bool
	K4Enabled                               bool
	KeepMajorVersion                        bool
	KeywordBoost12                          float64
	KeywordBoostingTraffic                  int
	KeywordCascading                        bool
	KeywordCascadingGlobal                  bool
	KeywordCascadingGlobalRead              bool
	KeywordCascadingLimit                   float64
	KeywordCascadingWeight                  float64
	KeywordClickSeed                        float64
	KeywordFileTraffic                      int
	KeywordGlobalMultiplier                 float64
	KeywordHarmonyTraffic                   int
	KeywordLastestClickedPrioritizedTraffic int
	KeywordPageViewsOnlyTraffic             int
	KeywordProviderIdAuditing               bool
	KeywordRPCDisabledTraffic               int
	KeywordRPCTrafficDivision               []int
	KeywordRPCWeightTraffic                 int
	KeywordRPMDefautToURLOnlyTraffic        int
	KeywordRPMDefautToURLTraffic            int
	KeywordRPMDomainClickLimit              float64
	KeywordRPMKeywordLimit                  int
	KeywordRPMRPCTraffic                    int
	KeywordRPMTraffic                       int
	KeywordSimilarityFactor                 int
	KeywordSimilarityTraffic                int
	KeywordsPrefix                          string
	KeywordStrategyAerospikeEnabled         bool
	KeywordStrategyBiasTraffic              int
	KeywordStrategyBiasUseRPCTraffic        int
	KeywordStrategyExplorationMultiplier    bool
	KeywordStrategyRPCThreshold             float64
	KeywordStrategyRPMEnabled               bool
	KeywordStrategyTraffic                  int
	KeywordTypeStrategyWeightLimit          float64
	KeywordViewsThreshold                   float64
	L2AGranularity                          float64
	L2AModelName                            string
	L2AModelTraffic                         int
	LatestKeywordMax                        bool
	LatestKeywordWeight                     float64
	LatestKeywordWeightInViews              float64
	LatestRPC                               int
	LatestRPCMax                            int
	LoggingPercentage                       float64
	LogKeywordData                          bool
	MaxBudget                               float64
	MaxDomainKeywords                       int
	MaxKeywords                             int
	MaxKeywordsReadLimit                    int
	MaxL2A                                  float64
	MaxR2A                                  float64
	MinR2A                                  float64
	MinimumViewabilityThreshold             float64
	MinL2A                                  float64
	MinRPC                                  float64
	MinRPCBlockedDomains                    []string
	Multiplier                              float64
	NewViewabilityBucket                    bool
	Normalize2                              bool
	Normalize3                              bool
	OnlyProvider60Traffic                   bool
	PageViewSeed                            float64
	PatternMultiplierTraffic                int
	Provider62To60Enabled                   bool
	ProviderGroup10                         bool
	ProviderIdAuditing                      bool
	ProviderRatioRPCTraffic                 int
	R2AAdditionFactor                       float64
	R2AExploitationWeight                   float64
	ReplaceSellerTagId                      int
	RevenueModelTrafficPercentage           int
	RevenueSeed                             float64
	RPCBuckets                              []RPCBucket
	RPCCap                                  float64
	RPCExpiry                               float64
	RPMBias                                 bool
	RPMDetailClickThreshold                 float64
	RPMDetailClickThresholdAbtestBuckets    []ClickThresholdBucket
	RPMUnbias                               bool
	RunWeightedOnSemiExploration            bool
	SegmentsToBid                           map[string]float64
	SellerTagBiasThreshold                  float64
	SellerUserIdLimit                       int
	SemiExplorationActualL2A                bool
	SemiExplorationMultiplier               float64
	SemiExplorationThreshold                float64
	SemiExplorationTraffic                  int
	SemiFeedbackDirect                      bool
	SendKeywords                            int
	SendKeywordsBlockedStates               []string
	SendKeywordsLength                      int
	SizeBasedUAIPLimit                      int
	SlidingBucketPower                      float64
	SlidingClickedKeywordPower              float64
	SlidingDisplayedKeywordPower            float64
	SlidingKeywordTraffic                   int
	SlidingRPCExpiry                        float64
	SlidingRPCExpiryTraffic                 int
	SoftCapMultipliers                      []float64
	SoftCaps                                []float64
	StateLevelRPC                           bool
	StateRPCClickThreshold                  float64
	StopLossMode                            int
	StopLossTimeZone                        string
	SwitchAuditKeyForProvider62             bool
	TakeUrlRPCFeedback                      bool
	TargetingLevel                          int
	TargetingMode                           int
	TemplateTraffic                         int
	Templates                               []string
	TemplateWeightStrategy                  int
	TrimCreativeId                          int
	TrimGeoCriteria                         int
	TrimSellerTag                           int
	TrimStateHour                           int
	TrimUserAgent                           int
	UAIPLimit                               int
	UhdUrlAlgoPercentage                    []int
	UhdUrlPredictionPercentage              int
	UhdUrlL2RSortingPercentage              int
	UniqueClickedKeywordsThreshold          int
	URLRPCTraffic                           int
	UserAgentGlobalBiasEnabled              bool
	UserAgentGlobalBiasClickThreshold       float64
	UserAgentGlobalBiasTraffic              int
	UserAgentGlobalBiasLowerLimit           float64
	UserAgentGlobalBiasUpperLimit           float64
	UseAdBlockKey                           bool
	UseOperaAsChrome                        bool
	UserAgentBiasDisabled                   bool
	UserAgentThreshold                      float64
	UseWidgetL2AMap                         bool
	WidgetL2AModelTrafficPercent            int
	Visitor2Bias                            float64
	VisitorBias                             float64
	VisitorLimit                            int
	VisitorToUserAgent                      bool
	VisitorViewsBlocking                    bool
	WeightedKeywordStrategyPower            float64
	XlearnR2AModelTrafficPercentage         int
	XLearnServerIP                          string
=======
	ActualL2ATraffic                         int
	AdBlockConfig                            AbkConfig
	AddCreativeInURL                         bool
	AdditionFactor                           float64
	AdditionFactorClickLimit                 float64
	AddSellerTagInUrl                        bool
	AddTemplateInURL                         bool
	AdjustDomainL2ATraffic                   int
	AdvertiserAuditing                       bool
	AdvertiserDetailClickThreshold           float64
	AdvertiserDetailExpiry                   float64
	AdvertiserExpiry                         int64
	AdTagLevelSeed                           bool
	AerospikeCache                           bool
	AerospikeFeedbackBlocked                 bool
	AerospikeKeywordRPCReadPercentage        int
	AerospikeKwdStrategyPercent              int
	AerospikeReadStrategyPercent             int
	AllowUnknownSellerTagId                  bool
	AllowUnknownViewability                  bool
	AllowZeroBiasInFeedback                  bool
	AlternateMapTraffic                      int
	AlternateBaseMapToggle                   bool
	AlternateL2aBaseTraffic                  map[string]int
	AlternateL2aBaseL2aFiles                 map[string]string
	AlternateL2aBaseWriteL2aFiles            map[string]string
	AlwaysAddToBase                          bool
	ApplyBrowserMultiplier                   bool
	ApplyManualPattern                       bool
	AuctionType1Multiplier                   float64
	AuctionType2Multiplier                   float64
	AutoModelUsed                            bool
	BaseMapSwitchAdclickThreshold            int
	BehaviouralTargetingConfig               BehaviouralTargetingConfig
	BiasClickThreshold                       float64
	Biases                                   string
	BiasFeedbackTill                         float64
	BiasModelName                            []string
	BiasModelTraffic                         []int
	BiasModelTrafficOverall                  int
	BiasVersion2Enabled                      bool
	BiasVersion2Buckets                      []Bucket
	BidderRPCTraffic                         int
	BidFloorInflationDomains                 []string
	BidFloorInflationTraffic                 int
	BidFloorInflationLimit                   float64
	BlockedAsn                               []string
	BlockDueToLogging                        bool
	BlockedTemplates                         []string
	BlockedTrafficPercent                    int
	BlockMaxProvider                         bool
	BlockNonUTM                              bool
	BlockSpam                                bool
	BrowserLevelKeywordTraffic               int
	BrowserRPCTraffic                        int
	ByPassKeywordClicksTrafficPercentage     int
	CanadaKeywords                           bool
	CacheRpcPredictionTraffic                int
	CacheRpcTime                             int
	CascadingL2AClickRange                   []float64
	CascadingL2AClickThreshold               float64
	CascadingR2AClickThreshold               float64
	CascadingR2AWeight                       float64
	CatboostL2AModelClickThreshold           float64
	CatboostL2AModelTraffic                  int
	CatboostL2AUrlSubTraffic                 int
	CatboostModelName                        string
	CatboostR2AModelName                     string
	CatboostRPCModelName                     string
	CbsL2aApiPath                            string
	CeaseExplorationPageviewFactor           float64
	Checksum                                 string
	ClickedKeywordBuckets                    int
	ClickedKeywordsExpiry                    int64
	ClickedKeywordsThreshold                 float64
	ClickedKeywordsWeight                    float64
	ClickedKeywordsWhitelistLimit            int64
	ClickRatio                               float64
	CommercialPatternTrafficPercentage       int
	ConsensusClickThreshold                  float64
	ConsiderFeatureMapping                   bool
	ConsiderTopLevelR2A                      bool
	CountryLevelStopLoss                     map[string]float64
	CreativeLevelKeywords                    bool
	CustomerURLRPCTraffic                    int
	DeviceOSThreshold                        float64
	DisableHomePageBlocking                  bool
	DisableRPCExploration                    bool
	Disagreement                             float64
	DiscrepancyMultiplierEnabled             bool
	DiscrepancyMultiplierLimit               float64
	DisplayedKeywordBuckets                  int
	DisplayedKeywordsExpiry                  int64
	DisplayedKeywordsHalvingFactor           float64
	DisplayedKeywordsThreshold               float64
	DomainL2ARatioBoostTraffic               int
	DomainRPCTraffic                         int
	DynamicExplorationEnabled                bool
	DynamicMultiplierEnabled                 bool
	EcpiTrafficPercentage                    int
	EnabledBiases                            []string
	ExploitationClickLowerLimit              float64
	ExploitationClickThreshold               float64
	ExploitationClickUpperLimit              float64
	ExploitationMinimumDepth                 int
	ExploitationWeight                       float64
	ExploitationWeightThreshold              float64
	ExploitationWeightThresholdAbtestBuckets []Bucket
	ExplorationClickThreshold                float64
	ExplorationHardCap                       float64
	ExplorationMaxL2ATraffic                 int
	ExplorationMultiplier                    float64
	ExplorationPercent                       int
	ExplorationSpeedDamper                   float64
	FailoverEcpi                             float64
	FailoverR2A                              float64
	FailoverRPC                              float64
	FailoverRPM                              bool
	FailoverStrategyEnabled                  bool
	FailoverStrategyMultiplier               float64
	FeatureMappingBucketTraffic              int
	FeedbackTill                             float64
	FeedbackWeight                           float64
	FilterSlidingKeywords                    bool
	FloorPrice                               float64
	ForbesAdvisorRPCTraffic                  int
	ForbesRPCExpiry                          float64
	ForbesRPCRectify                         bool
	ForbesURLTransformation                  bool
	ForceTemplateId                          string
	ForcedProviderGroup                      string
	GlobalBiasFeedbackEnabled                bool
	GlobalBiasTrafficPercent                 int
	GlobalClickLimit                         float64
	HardCap                                  float64
	HashUserAgent                            bool
	HierarchyMultiplier                      float64
	HourMultiplier                           map[string]float64
	IgnoreVisibility                         bool
	IgnoreZeroInfoDataTraffic                int
	IgnoreZeroInfoThreshold                  float64
	IhaPercentage                            int
	InitialWeight                            float64
	IntegrationBias                          bool
	IntegrationFile                          string
	IPBiasClickThreshold                     float64
	IpBiasDisabledTraffic                    int
	IPBiasViewsThreshold                     float64
	IPBiasLowerLimit                         float64
	IPBiasLimit                              float64
	IPBiasTraffic                            int
	IPBiasTrafficSuffix                      string
	IPBiasFull                               bool
	IPBiasBClass                             bool
	IPStateBiasDisabled                      bool
	IPUnbiasEnabled                          bool
	K4Enabled                                bool
	KeepMajorVersion                         bool
	KeywordBoost12                           float64
	KeywordBoostingTraffic                   int
	KeywordCascading                         bool
	KeywordCascadingGlobal                   bool
	KeywordCascadingGlobalRead               bool
	KeywordCascadingLimit                    float64
	KeywordCascadingWeight                   float64
	KeywordClickSeed                         float64
	KeywordFileTraffic                       int
	KeywordGlobalMultiplier                  float64
	KeywordHarmonyTraffic                    int
	KeywordLastestClickedPrioritizedTraffic  int
	KeywordPageViewsOnlyTraffic              int
	KeywordProviderIdAuditing                bool
	KeywordRPCDisabledTraffic                int
	KeywordRPCTrafficDivision                []int
	KeywordRPCWeightTraffic                  int
	KeywordRPMDefautToURLOnlyTraffic         int
	KeywordRPMDefautToURLTraffic             int
	KeywordRPMDomainClickLimit               float64
	KeywordRPMKeywordLimit                   int
	KeywordRPMRPCTraffic                     int
	KeywordRPMTraffic                        int
	KeywordSimilarityFactor                  int
	KeywordSimilarityTraffic                 int
	KeywordsPrefix                           string
	KeywordStrategyAerospikeEnabled          bool
	KeywordStrategyBiasTraffic               int
	KeywordStrategyBiasUseRPCTraffic         int
	KeywordStrategyExplorationMultiplier     bool
	KeywordStrategyRPCThreshold              float64
	KeywordStrategyRPMEnabled                bool
	KeywordStrategyTraffic                   int
	KeywordTypeStrategyWeightLimit           float64
	KeywordViewsThreshold                    float64
	L2AFoldingSelectorBuckets                []Bucket
	L2AGranularity                           float64
	L2AModelName                             string
	L2AModelTraffic                          int
	LatestKeywordMax                         bool
	LatestKeywordWeight                      float64
	LatestKeywordWeightInViews               float64
	LatestRPC                                int
	LatestRPCMax                             int
	LoggingPercentage                        float64
	LogKeywordData                           bool
	MaxBudget                                float64
	MaxDomainKeywords                        int
	MaxKeywords                              int
	MaxKeywordsReadLimit                     int
	MaxL2A                                   float64
	MaxR2A                                   float64
	MinR2A                                   float64
	MinimumViewabilityThreshold              float64
	MinL2A                                   float64
	MinRPC                                   float64
	MinRPCBlockedDomains                     []string
	Multiplier                               float64
	MultiplierRestriction                    float64
	NewViewabilityBucket                     bool
	Normalize2                               bool
	Normalize3                               bool
	OnlyProvider60Traffic                    bool
	PageViewSeed                             float64
	PatternMultiplierTraffic                 int
	Provider62To60Enabled                    bool
	ProviderGroup10                          bool
	ProviderIdAuditing                       bool
	ProviderRatioRPCTraffic                  int
	QuarterlyCumulativeBudget                []float64
	R2AAdditionFactor                        float64
	R2AExploitationWeight                    float64
	ReplaceSellerTagId                       int
	ReplacePatternInPublisherURL             map[string]string
	RevenueModelTrafficPercentage            int
	RevenueSeed                              float64
	RPCBuckets                               []RPCBucket
	RPCCap                                   float64
	RPCExpiryInHours                         int64
	RPMBias                                  bool
	RPMDetailClickThreshold                  int64
	RPMKeyWordHierarchyBuckets               []Bucket
	RPMUnbias                                bool
	RunWeightedOnSemiExploration             bool
	SegmentBiasPercentage                    int
	SegmentsToBid                            map[string]float64
	SellerTagBiasThreshold                   float64
	SellerUserIdLimit                        int
	SemiExplorationActualL2A                 bool
	SemiExplorationMultiplier                float64
	SemiExplorationThreshold                 float64
	SemiExplorationTraffic                   int
	SemiFeedbackDirect                       bool
	SendKeywords                             int
	SendKeywordsBlockedStates                []string
	SendKeywordsLength                       int
	SizeBasedUAIPLimit                       int
	SlidingBucketPower                       float64
	SlidingClickedKeywordPower               float64
	SlidingDisplayedKeywordPower             float64
	SlidingKeywordTraffic                    int
	FixedRPCTraffic                          int
	SlidingRPCExpiry                         float64
	SlidingRPCExpiryTraffic                  int
	SoftCapMultipliers                       []float64
	SoftCaps                                 []float64
	StopLossMode                             int
	StopLossTimeZone                         string
	SwitchAuditKeyForProvider62              bool
	TargetingLevel                           int
	TargetingMode                            int
	TemplateTraffic                          int
	Templates                                []string
	TemplateWeightStrategy                   int
	TimerBinName                             string
	TrimCreativeId                           int
	TrimGeoCriteria                          int
	TrimSellerTag                            int
	TrimStateHour                            int
	TrimUserAgent                            int
	UAIPLimit                                int
	UhdUrlAlgoPercentage                     []int
	UhdUrlPredictionPercentage               int
	UhdUrlL2RSortingPercentage               int
	UniqueClickedKeywordsThreshold           int
	URLRPCTraffic                            int
	UserAgentGlobalBiasEnabled               bool
	UserAgentGlobalBiasClickThreshold        float64
	UserAgentGlobalBiasTraffic               int
	UserAgentGlobalBiasLowerLimit            float64
	UserAgentGlobalBiasUpperLimit            float64
	UseAdBlockKey                            bool
	UseOperaAsChrome                         bool
	UserAgentBiasDisabled                    bool
	UserAgentThreshold                       float64
	UseWidgetL2AMap                          bool
	WidgetL2AModelTrafficPercent             int
	Visitor2Bias                             float64
	VisitorBias                              float64
	VisitorLimit                             int
	VisitorToUserAgent                       bool
	VisitorViewsBlocking                     bool
	WeightedKeywordStrategyPower             float64
	XlearnR2AModelTrafficPercentage          int
	XLearnServerIP                           string